### ISSUE TITLE
raceRoundEntries table showing car columns when series only has 1 car

### ISSUE THREAD

**Issue by TJSteel** [TJSteel/OnlineRacingManager#100]
example, see page: https://online-racing-manager.herokuapp.com/raceRound/5e60303bf5d1b80004bcf7db

it displays car and car class, however as the car choice isn't sent with an entry to a single car championship, it will always be null, therefore the car and car class column should be hidden

**Comment by TJSteel** [comment]
to point you in the right direction,

the files that control this are stored here:
src/app/core/screens/raceRoundEntries/race-round-entry-table

I could hint further, but then I'd be fixing it for you

**Comment by madalinaj730** [comment]
issue fixed
