### ISSUE TITLE
Added sign in button next to event name

### ISSUE THREAD

**Issue by Scholesy46** [TJSteel/OnlineRacingManager#101]
When you tab over to the rounds table could we get a Sign in button added to the right hand side that allows drivers to sign up that way as apposed to going into the round itself. see attached image as example:
https://cdn.discordapp.com/attachments/256435695781019648/689603135970476034/unknown.png

**Comment by TJSteel** [comment]
not really sure this is needed, signing in is already implemented via clicking the link on that table to take you to the round page,

will delay looking at this one until all critical functionality has been implemented

**Comment by TJSteel** [comment]
Completed today by @kvonaute
