### ISSUE TITLE
add ability to temp ban someone from signing into races

### ISSUE THREAD

**Issue by TJSteel** [TJSteel/OnlineRacingManager#152]

**Comment by 97stj** [comment]
I think this would link in with issue #84 as (from my understanding, I could be wrong), it should only be the stewards or staff dealing with user bans. The current roles would be too broad

**Comment by TJSteel** [comment]
@97stj yeah it kinda will, I should really have made an issue specifically for the permissions upgrade too so we could link it to that but I guess I was a bit lazy there lol

**Comment by TJSteel** [comment]
blocked by #84 as above

**Comment by TJSteel** [comment]
no longer blocked, we have the permissions update done now

for this however I'm not sure a perm group should dictate if a user can do something,

possibly an additional field on the user (banExpiry) and if the date is in the future, they get auth denied?

maybe still allow login though, but just fail auth on anything other than login with a banExpiry

Perma ban can be done by just removing all roles
