### ISSUE TITLE
Remove race sign in.

### ISSUE THREAD

**Issue by SmileykidCoder** [TJSteel/OnlineRacingManager#161]
Please could race sign in be removed as pre orm this was not an issue for any championships so you registered for the championship and you could race now people are losing out on champions due to forgetting to sign in or just not being able to.

Standings should be settled on track not by who signed in.

**Comment by TJSteel** [comment]
Hey @SmileykidCoder 

Pre ORM this was actually a thing and always had been, example, see TCC 2018: https://forums.theonlineracingassociation.com/t19117-tcc-sign-in-live-timing

only difference being we had a google form for signing in, we trialed removing it last season, and while it was maybe more convenient to not have to sign in, when we have an event with over 100 people registered, and we're sending invites to people who aren't even intending on racing, it causes unnecessary work for staff,

Or if you want to go right back to TCC Season 1, when posting to the forum was your sign in: https://forums.theonlineracingassociation.com/t56-round-1-maple-valley-25-05-08-9pm

Which posting to a forum wasn't so bad with only 17 drivers racing, but you can see how this spirals out of control when we're now hosting 100+ drivers

Just as an example, take a look at GTCC EU Standings,
165 drivers,
25 of whom didn't attend a single race, therefore with those alone, 3 invites each per round causes staff to send 525 unwanted invites, however if you look at the total rounds missed (eg, those where a driver registered and did 1 round (missing 6 of them)

Or worst case scenario, going to Round 7 where only 75 people signed in, meaning we would be trying to invite 90 people, 270 invites to those that weren't even intending on racing, 

So yeah I can understand the frustration of missing a sign in, but hopefully the above puts into perspective the reason behind why we do it,

we are looking at other ways of improving this though, such as having the sign in's open for 8 days, meaning you can sign in for round 2, on the day of round 1 meaning you could sign in for next week while waiting between quali and the race.
