### ISSUE TITLE
Vehicle name issues in the database

### ISSUE THREAD

**Issue by Scholesy46** [TJSteel/OnlineRacingManager#51]
When added to the list of car the 2017 Aston Martin V12 Vantage GT3 has the model name "2017er Aston Martin #7 V12 Vantage GT3". Additionally the accent on the name Citroen causes some display issues with the name being presented as "CitroÃ«n"

**Comment by TJSteel** [comment]
let's merge this issue with the below as the work to fix one will fix both: https://github.com/TJSteel/OnlineRacingManager/issues/52
