### ISSUE TITLE
Vehicle Selection

### ISSUE THREAD

**Issue by Scholesy46** [TJSteel/OnlineRacingManager#52]
When two cars have the same model name it is very difficult to tell which car is which. Example: For the CT Cup test series there are two BMW M3's, one 1997 and the other 2005 however in the Car Choice drop down they are both listed as only M3

**Comment by TJSteel** [comment]
When added to the list of car the 2017 Aston Martin V12 Vantage GT3 has the model name "2017er Aston Martin #7 V12 Vantage GT3". Additionally the accent on the name Citroen causes some display issues with the name being presented as "CitroÃ«n"

**Comment by TJSteel** [comment]
updated db entries for the aston and citroen

found for the duplicate model names, there are 77 cars which would need updating, appending the year to this instead would remove the duplicate issue so will look at this later

**Comment by TJSteel** [comment]
added year to all car choice displays to ensure uniqueness
