### ISSUE TITLE
Hyphens and special characters aren't allowed in team names

### ISSUE THREAD

**Issue by Scholesy46** [TJSteel/OnlineRacingManager#53]
Hyphenated words such as Z-Team aren't allowed in the Team Name text box when entering a team name

**Comment by TJSteel** [comment]
no special characters should be allowed at all for this to be honest, that was the original idea,
however looking at my regex for this it's a little off

`entry.teamName.match('^[A-z0-9 ]+$')`

if you look at an ascii table: http://www.asciitable.com/
A-z covers the characters inbetween Z and a too, which shouldn't be allowed

what do you think we should be allowing character wise to a team name?

I've updated the match to this

`entry.teamName.match('^[A-Za-z0-9 \']+$')`

which will allow numbers, letters, space and '

does this seem good enough @Scholesy46 ?
