### ISSUE TITLE
Unknown Error Occurred, details are: [object Object]

### ISSUE THREAD

**Issue by Scholesy46** [TJSteel/OnlineRacingManager#55]
https://cdn.discordapp.com/attachments/653378330791378944/674330659665346571/Screenshot_2020-02-04_at_19.09.09.png

**Comment by Scholesy46** [comment]
Error occurs on MAC OS as date and month are swapped when trying to register the date

**Comment by TJSteel** [comment]
Displaying server messages needs updating, if the error is an object rather than a string, the string display cannot handle it.
