### ISSUE TITLE
Ability to choose a reverse grid for race 1 and/or race 2

### ISSUE THREAD

**Issue by Scholesy46** [TJSteel/OnlineRacingManager#60]
A couple of TORA events run reverse grid orders. American Iron splits all results into two lobbies and then reverses the grid order, excluding DNQ's, for the race and in GT Cup race one was based on qualifying position while race 2 was based on the reverse of race 2 results, excluding all DNS and DNF results.

This could be done by having a check box when creating a race that gives you the option for the race to have a reverse grid

**Comment by TJSteel** [comment]
Reverse grid will need an option of a percentage adding,

Spec Miata is using a 50% reverse grid (16 lobby, top 8 reversed)

when adding a race, the reverse grid option should be a dropdown of Yes, No, Percent

If Percent, give an option of 0-100, to be stored in the db as a number regardless (yes = 100, no = 0, percent = whatever percentage is entered)
