### ISSUE TITLE
Ability to filter the teams standings to classes in the team standings

### ISSUE THREAD

**Issue by Scholesy46** [TJSteel/OnlineRacingManager#63]
in the team standings page for the gt cup all the teams are classed under one table despite the top two teams in the table, Raging Lizard Esports and DareDevil Motorsports, being in separate classes and thus not in a battle with each other

**Comment by Scholesy46** [comment]
A potential addition down the round, have individual tables for separate classes that can be toggled between in similar to those seen on this website https://sportscarchampionship.imsa.com/standings whereby above the points table there is a button that can be pressed allowing you to flick between each points table. Again though a down the road enhancement

**Comment by TJSteel** [comment]
forgot to close, was implemented a few changes back
